feat: Add enablePictureInPicture option
videojs/videojs.com pull request #168
Opened 2023-03-07 16:47 UTC by mister-ben

Documents `enableDocumentPictureInPicture` option for videojs/video.js/pull/8113

2023-04-06 06:34 UTC, Chocobozzz commented on src/mdx-pages/guides/options.mdx
> +Currently this is avialable in Chrome 111+ as an origin trial.
Typo: `avialable` :)

2023-04-24 14:58 UTC, wseymour15 requested changes
Looks good! Approved once the typos and nits are updated.

2023-04-24 14:58 UTC, wseymour15 commented on src/mdx-pages/guides/options.mdx
> +If `true`, switching the video element into picture-in-picture is disabled. Defautl is `false`.
Typo: "Default"

2023-04-24 14:58 UTC, wseymour15 commented on src/mdx-pages/guides/options.mdx
> +If `true`, the [documentPictureInPicture API](https://developer.chrome.com/docs/web-platform/document-picture-in-picture/) will be used for picture in picture, if available. Defaults to `false`, but
nit: I think we want to include hyphens in "picture-in-picture", just to keep the doc consistent.

2023-04-24 14:58 UTC, wseymour15 commented on src/templates/HomeTemplate.jsx
> +        {/* Oriign trial for documentPictureInPicture */}
typo: "Origin"

2023-04-25 14:37 UTC, wseymour15 approved these changes

2023-04-25 14:44 UTC, merged